import { DEFAULT_SETTINGS } from "./config.js";
import { createConditionAssessment } from "./condition-assistant.js";

export const SMART_LIST_DEFINITIONS_LOOKUP = Object.freeze({
  recent: { title: "Neu im Archiv", description: "Zuletzt hinzugefügte oder aktualisierte Bände" },
  unread: { title: "Noch ungelesen", description: "Bände, von denen noch kein Exemplar gelesen wurde" },
  duplicates: { title: "Mehrfach vorhanden", description: "Ausgaben mit mindestens zwei physischen Exemplaren" },
  sealed: { title: "Folierte Exemplare", description: "Ausgaben mit mindestens einem folierten Exemplar" },
  "needs-care": { title: "Zustand 3 oder schwächer", description: "Bände, die genauer geprüft oder ersetzt werden könnten" },
  metadata: { title: "Daten ergänzen", description: "Titel, Jahr oder Duckipedia-Verknüpfung fehlen" },
  "no-cover": { title: "Ohne Cover", description: "Noch ohne eigenes oder geladenes Coverbild" },
  "current-year": { title: "Aktueller Jahrgang", description: "Bände aus dem laufenden Kalenderjahr" }
});

export function createInitialAppState() {
  return {
  archiveGraph: { series: [], issues: [], copies: [] },
  archiveRuntimeSource: "",
  collectionEntries: [],
  filteredComics: [],
  missingGroups: [],
  settings: {
    ...DEFAULT_SETTINGS,
    customSeriesConfigs: [],
    knownHighestBandBySeries: {},
    missingBandDetails: {},
    fleaMarketSession: { items: {}, updatedAt: null }
  },
  editingId: null,
  editingComic: null,
  importBackup: null,
  importReturnTarget: null,
  waitingServiceWorker: null,
  selectedMissingBand: null,
  scannerResult: null,
  scannerLookupController: null,
  scannerQueue: [],
  scannerMode: "fast",
  scannerSessionScans: 0,
  scannerQueueLookups: new Map(),
  scannerFlashTimer: null,
  formMetadata: null,
  pendingCover: null,
  removeCoverRequested: false,
  formCoverObjectUrl: null,
  formHasLocalCover: false,
  cardCoverObjectUrls: new Set(),
  metadataLookupTimer: null,
  enrichmentRunning: false,
  collectionScope: "main",
  collectionPreset: {},
  collectionReturnTarget: "home",
  localCoverIds: new Set(),
  missingScope: "main",
  missingReturnTarget: "home",
  openMissingSeries: new Set(),
  missingLookupSequence: 0,
  fleaMarketScope: "all",
  selectedCopyComicId: null,
  copyManagerDraft: [],
  archiveCoreStatus: null,
  dataStackStatus: null,
  conditionGuideReturnTarget: null,
  conditionAssistantStep: 1,
  conditionAssistantAssessment: createConditionAssessment(),
  conditionAssistantTarget: null,
  editingCustomSeriesName: "",
  selectedCalendarEventId: null,
  calendarImporting: false,
  calendarCatalog: [],
  calendarCatalogUpdatedAt: "",
  calendarCatalogLoading: false,
  calendarFilter: "all",
  calendarSearch: "",
  latestDiagnosticReport: null,
  diagnosticsRunning: false,
  shelfCoverResolutionPromises: new Map(),
  releaseRadarFilter: "open",
  releaseRadarReturnTarget: "home",
  releaseLinkEventId: null,
  collectorMission: null,
  currentMilestones: [],
  milestoneSyncPending: false,
  milestoneCelebrationTimer: null,
  shareCardRendering: false
};
}
